In [1]:
import torch
from torch import nn

INPUT_FEATURES = 2
OUTPUT_NEURONS = 1

SAMPLE_NUM = 5
TARGET_WEIGHT = torch.tensor([1.0, 2.0])
TARGET_BIAS = 3.0

learning_rate = 1e-2
EPOCHS = 10000

class OptTest(nn.Module):
    def __init__(self):
        super().__init__()

        self.weights = nn.Parameter(torch.randn(INPUT_FEATURES))
        self.bias = nn.Parameter(torch.randn(OUTPUT_NEURONS))        

    def forward(self, input):
        return input.multiply(self.weights) + self.bias
    
    def train_loop(self, xs, ys, loss_fn, optimizer):
        size = len(xs)
    
        pred = self(xs)

        loss = loss_fn(pred, ys)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

model = OptTest()

xs = torch.randn(SAMPLE_NUM, INPUT_FEATURES)
ys = xs.multiply(TARGET_WEIGHT) + TARGET_BIAS

loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for param in model.parameters():
    print(param)

for t in range(EPOCHS):
    model.train_loop(xs, ys, loss_fn, optimizer)

for param in model.parameters():
    print(param)

Parameter containing:
tensor([1.1989, 0.6187], requires_grad=True)
Parameter containing:
tensor([-0.0314], requires_grad=True)
Parameter containing:
tensor([1.0000, 2.0000], requires_grad=True)
Parameter containing:
tensor([3.0000], requires_grad=True)


In [2]:
import torch
import torch.nn as nn

SAMPLE_NUM = 5
TARGET_WEIGHT = torch.tensor([1.0, 2.0])
TARGET_BIAS = 3.0
INPUT_FEATURES = 2
OUTPUT_NEURONS = 1

learning_rate = 1e-2
epochs = 10000

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer1 = nn.Linear(INPUT_FEATURES, OUTPUT_NEURONS)

    def forward(self, input):

        output = self.layer1(input)

        return output

    def train_loop(self, xs, ys, loss_fn, optimizer):
        size = len(xs)
    
        pred = self(xs)

        loss = loss_fn(pred, ys)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

model = NeuralNetwork()

xs = torch.randn(SAMPLE_NUM, INPUT_FEATURES)
ys = torch.mv(xs, TARGET_WEIGHT).reshape(SAMPLE_NUM, OUTPUT_NEURONS) + TARGET_BIAS

loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for param in model.parameters():
    print(param)

for t in range(epochs):
    model.train_loop(xs, ys, loss_fn, optimizer)

for param in model.parameters():
    print(param)

Parameter containing:
tensor([[-0.5766,  0.1180]], requires_grad=True)
Parameter containing:
tensor([-0.5915], requires_grad=True)
Parameter containing:
tensor([[1.0001, 1.9999]], requires_grad=True)
Parameter containing:
tensor([3.0000], requires_grad=True)
